#!/bin/bash
<%#
kind: user_data
name: KVM User Data
model: ProvisioningTemplate
oses:
- CentOS
- Redhat
-%>

# Get variables
<%
  rhel_compatible = @host.operatingsystem.family == 'Redhat' && @host.operatingsystem.name != 'Fedora'
  pm_set = @host.puppetmaster.empty? ? false : true
  proxy_uri = host_param('http-proxy') ? "http://#{host_param('http-proxy')}:#{host_param('http-proxy-port')}" : nil
  puppet_enabled = pm_set || host_param_true?('force-puppet')
%>

# Fix /etc/hosts
<%= snippet 'fix_hosts' %>

# Setup networking
<%= snippet('setup_nic') %>

# Register host
<%= snippet 'redhat_register' %>

# Update all erratas
yum -t -y update

#update local time
echo "Installing common resources"
yum -y install ntpdate vim tree bind-utils git telnet
/usr/sbin/ntpdate -sub <%= host_param('ntp-server') || '0.fedora.pool.ntp.org' %>
/usr/sbin/hwclock --systohc

# Configure SSH Keys
<%= snippet('remote_ssh_keys') %>

# Configure puppet
<%= snippet 'puppet_setup' %>

# we dont want cloud init to mess up our /etc/hosts
sed -i 's|^ - update_etc_hosts||g' /etc/cloud/cloud.cfg

# Call home, we are done
/usr/bin/curl -o /dev/null -k '<%= foreman_url('built') %>'

# sleep and reboot
sleep 3
reboot



